CREATE TABLE LIKER_ARTICLE
(
    ID         SERIAL PRIMARY KEY NOT NULL,
    LIKER_ID   BIGINT             NOT NULL,
    ARTICLE_ID BIGINT             NOT NULL,
    FOREIGN KEY (LIKER_ID) REFERENCES "user",
    FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE
);
